### ISSUE TITLE
请问网易云的红心会同步到spotify的红心还是歌单？

### ISSUE THREAD

**Issue by sailcom** [GalvinGao/NeteaseRecommendationSync#22]
可以将网易云的红心，同步到spotify的红心(点赞的歌曲)中吗？

**Comment by GalvinGao** [comment]
hmmm，这个暂时没有计划，不过欢迎PR！（
作者暂时用不到这个功能的说x

**Comment by sailcom** [comment]
已经迁移好了。
不用做这个功能，因为从歌单可以一键加红心，很方便。
感谢大神给我们提供了一个这么方便的工具
